config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comments
resources :follows
resources :forums
resources :posts
resources :static_pages
resources :users

    root to: "comments#index"
  end

  get 'forums/index'

  get 'forums/show'

  get 'forums/new'

  get 'forums/edit'

  mount Ckeditor::Engine => '/ckeditor'

  
  root "static_pages#home"
  get 'profile', to: "static_pages#profile"
  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"
  get 'major', to: "users#major",as: :major
  get 'terms', to: "static_pages#terms"
  get 'papermajor', to: "posts#papermajor"
  get 'forummajor', to: "forums#forummajor"
  get 'dashboard', to:"static_pages#dashboard"
  get 'auth/facebook', as: "login"
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'logout'   => 'sessions#destroy', as: "logout"
  
  get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"
  
  
  resources :users do
    resources :upvotes, only: :create
    resources :downvotes, only: :create
    resources :comments
  end
  
  resources :users do
  member do
    get 'clip', to: "users#clip"
    get 'show_pdf', to: "users#show_pdf" 
    get :follow
    post :follow
    get :unfollow
    get 'friends', to: "users#friends"
    post 'friends', to: "users#friends"
    put "like", to: "users#upvote"
    put "dislike", to: "users#downvote"
        end
  end
  
  resources :posts do
  resources :comments
  end
  
  resources :posts do 
    member do
      get 'like', to: "posts#like"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :forums do 
    member do
      get 'like', to: "forums#like"
      put "like", to: "forums#upvote"
      put "dislike", to: "forums#downvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :forums do
  resources :comments
  end
  
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/admin/static_pages_controller.rb
module Admin
  class StaticPagesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = StaticPage.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   StaticPage.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :set_pending, except: [:home,:terms,:profile,:dashboard]

    def home 
        if current_user.present?
         redirect_to users_path,notice: "#{current_user.name}さんとしてログインしています"
        end
    end
    
    def terms
        if current_user.present?
            set_pending
        end
    end
    
    def profile
        if current_user.present?
            set_pending
        end
    end
    
    def dashboard
        if current_user.present? #ログインしてたら
            set_pending
            @major = current_user.major #現在のユーザーのメジャーを取得
            @users = User.where("major = ?", @major) #現在のユーザーのメジャーと同一のメジャーのすべてを取り出す
            @posts = Post.where("major = ?", @major)
            @forums = Forum.where("major = ?",@major)
            
        else
            redirect_to root_path
        end
       
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/dashboard.html.erb
<% provide(:title, "ホーム") %>
<% if current_user.username.present? && current_user.email.present? %>

<div class="row">
    
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile" style="margin-top:40px"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12 profile-header">
            <%= image_tag current_user.attachment, :size =>"50x50" %>
            <%= link_to current_user.username, user_path(current_user)%>
            <% if current_user == current_user %>
            
            <% end %>
    
        </div>
        
          <div class="col-sm-12 col-xs-12 col-md-12" > <!-- ユーザーの属性 -->
          <div class="profile-left"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= current_user.years %></div>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= current_user.major %></div>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                <% current_user.interest_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                <% end %>
          </div>
          
          
          <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>プロフィール</div>
                <div style="padding:20px"><%= current_user.bio %></div>
            </div>
            
             <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>会ってみたい人</div>
                <div style="padding:20px"><%= current_user.people %></div>
            </div>
            
            
            
          </div>
    </div>
<!-----------------------------------------------論文アップしてみない？---------------------------------------------->
<% unless current_user.posts.present? %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile" >
        <div class="profile-header" style="text-align:center">論文を投稿してみませんか</div>
        <div class="text-center">論文を投稿すると、よりあなたの興味・関心がわかりやすくなり、コンタクトリクエストをもらいやすくなります。</br>
            論文のタイトルと内容だけでよいので、投稿してみましょう。ファイルは後からも投稿できます。
        </div>
        <div class="text-center" style="margin-top:20px"><%= link_to "論文名と内容だけ登録する",new_post_path, class: :"login-button", style: :"color:#ffffff" %></div>

    </div> 
    
<% end %>
<!-----------------------------------------------おすすめトップ---------------------------------------------->

    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile" >
        <div class="profile-header " style="text-align:center"><%= current_user.username%>さんへのおすすめ</div>
    </div> 
    
<!-----------------------------------------------おすすめユーザー一覧---------------------------------------------->

    
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> 
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa; border-bottom:1px solid black">おすすめのユーザー(<%= @users.count %>)</div>
    
        
        <% @users.each do |user| %>
        <% unless user.username.nil? %>
        <div class="col-md-10 col-md-offset-1" id="posts-index">
        
            <div class="col-xs-12 col-sm-12 profile-header">
              <% if user.attachment.present? %>
                <%= image_tag user.attachment, :size =>"30x30" %><%= link_to user.username, user_path(user)%>
              <% else %>
                <%= image_tag "twitteregg.png", :size =>"30x30" %><%= link_to user.username, user_path(user)%>
              <% end %>
            </div>
            
             <div class="col-xs-12 col-sm-12" > 
                <div class="profile-left"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= user.years %></div>
                <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= user.major %></div>
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                    <% user.interest_list.each do |tag| %>
                        <span class="tag-button"><%= tag %></span>
                    <% end %>
             </div>
        </div>
        
    
   <% end %>
   <% end %>
   </div>
    
<!-----------------------------------------------おすすめ論文一覧---------------------------------------------->

    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa;border-bottom:1px solid black">おすすめの論文一覧(<%= @posts.count %>)</div>
    
    <!-------------------------------------------------論文ページ------------------------------------------------------------->
    <% @posts.each do |post| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class="profile-header"><%= link_to post.title, post_path(post)%> <small> /<%= time_ago_in_words(post.created_at)%>前</small></div>
                <div class="profile-left">
                    <% post.keyword_list.each do |tag| %>
                        <span class="tag-button"><%= tag %></span>
                    <% end %>
                </div>
                <div class ="profile-left"><%= image_tag post.user.attachment, :size =>"20x20" %> <%=link_to post.user.username,user_path(post.user)%></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %></div>
    
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>(<%= post.votes_for.size %>) <i class="fa fa-comment" aria-hidden="true"></i>(<%= post.comments.count %>)</div>

              <% if post.user == current_user %>
                  <%= link_to "編集する", edit_post_path(post), class: :"button-radius" %>
                  <%= link_to "消去する", post_path(post), method: :delete, class: :"button-radius" %>
              <% end %>
    </div>
     <% end %>
     </div>
   
    
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa;border-bottom:1px solid black">おすすめの質問一覧(<%= @forums.count %>)</div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
    <% @forums.each do |forum| %>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                    <div class="profile-header"><%= link_to forum.title, forum_path(forum)%> <small> /<%= time_ago_in_words(forum.created_at)%>前</small></div>
                    <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><span class="tag-button"><%= forum.major %></span></div>
                    <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>(<%= forum.votes_for.size %>) <i class="fa fa-comment" aria-hidden="true"></i>(<%= forum.comments.count %>)</div>
                  <% if forum.user == current_user %>
                      <%= link_to "編集する", edit_forum_path(forum), class: :"button-radius" %>
                      <%= link_to "消去する", forum_path(forum), method: :delete, class: :"button-radius" %>
                  <% end %>
        </div>
        <% end %>
    </div>

    
        
    
<% else %> <!-- まだログイン登録してない場合 --> 
<div id ="user_profile" class="text-center col-md-10 col-md-offset-1 " style="margin-top:60px">
  <div>ようこそ、<%= current_user.name %>さん。</br>CurioCityの使い方をご紹介します！</div>
</div>

<div id ="user_profile" class="text-center col-md-10 col-md-offset-1" style="margin-top:30px">
  <div class="profile-header">①プロフィールを編集しましょう。</div>
  <div>
      プロフィールを充実させると、あなたにおすすめのユーザーが紹介されます。
      また、連絡先を入力するとあなたに興味を持ったユーザーや、あなたが興味を持った人に、コンタクトリクエストが送信できます。
      お互いがコンタクトリクエストを承認すると、連絡先(メールアドレス、Twitter ID等）が「コンタクト」から見れるようになります。
  </div>
  <div class="">
      <%= image_tag "curiocityimage.png", style: :"max-width:100%; height:auto;margin:30px 0" %>
  </div>
</div>

<div id ="user_profile" class="text-center col-md-10 col-md-offset-1 " style="margin-top:30px">
  <div class="profile-header">②交流しよう</div>
  <div>
    面白そうな論文を読んだり、ユーザーのプロフィールを読んでみましょう。論文にコメントしたり、質問に答えることができます。
    興味をもったユーザーには、コンタクトリクエストを送ることができます。
  </div>
    <%= image_tag "findthesis.gif", style: :"max-width:100%; height:auto;margin:30px 0" %>

</div>

<div id ="user_profile" class="text-center col-md-10 col-md-offset-1 " style="margin-top:30px">
  <div class="profile-header">③質問や、論文を投稿してみよう！</div>
  <div>
        同じメジャーの先輩に質問してみたり</br>
        自分がどういう勉強に興味を持っているかを知らせるために、論文を投稿してみましょう！
  </div>
</div>
<div class="text-center" style="margin-top:20px"><%= link_to "まずはプロフィールを編集する", edit_user_path(current_user), class: :"login-button", style: :"color:#ffffff" %></div>




<% end %> <!-- まだログイン登録してない場合 --> 
</div>

app/views/static_pages/home.html.erb
<div class="row lp-1"> <!--- ランディングページ TOP lp1-------------------------------------->
  <div class="col-md-12 col-ms-12" style="text-align:center">
    <div class="message-large">Beyond Majors and Years</div>
    <div class="message-large" style="margin:30px 0">メジャー・学年を超えた<br>アカデミックSNS</br></div>
    <a href="/auth/facebook" class="login-button" style="color:#ffffff">Facebookから今すぐログインする</a>
  </div>
</div>

<div class="row"> <!--- ランディングページ TOP lp1-------------------------------------->
  <div class="col-md-12 col-ms-12" style="text-align:center;background-color:#FFFDF0;padding:100px 0">
    <div class="message-large"style="font-size:48px;color:#00B0BC">CurioCityとは</div>
    <div  style="margin:30px 0;font-size:36px;" >同じ興味・関心の人に出会える</br>アカデミックなプラットフォームです。</div>
    <div style="padding:10px 0">「何をどう学べばいいかだれかに聞きたい」「興味・関心が近い人に出会う場所がない」<br>CurioCityは、メジャー・学年を超えて、興味関心が近い人たちをつなげます。</div>
    <%= image_tag 'curiocityimage.png',style: :"width:auto;height:300px"%>
  </div>
  
  
</div>

<div class="row" style="padding:100px 0" id="user_profile"> <!-- 3つの特徴 -->
  
  <div class="col-md-12 col-ms-12" style="text-align:center">
    <div style="font-size:48px;color:#00B0BC">CurioCityでできること</div> <!-- タイトル -->
  </div>
  
  <div class="col-md-12" style="text-align:center">　<!-- FIND -->
    <div><i class="fa fa-search icon-large" aria-hidden="true" style="font-size:48px;color:#00B0BC"></i></div>
    <div class="icon-title" style="font-size:48px;color:#00B0BC">Find</div>
    <div class="icon-description" style="margin:30px 0;font-size:24px;">自分の興味・関心に近いユーザー、論文をメジャー別に探そう</div>
    <%= image_tag 'findthesis.gif',style: :"width:auto;height:400px"%>
  </div>
  
  <div class="col-md-12" style="text-align:center" style="margin:20px 0">
    <div><i class="fa fa-users icon-large" aria-hidden="true" style="margin:30px;font-size:48px;color:#00B0BC"></i></div>    
    <div class="icon-title" style="font-size:48px;color:#00B0BC">Interact</div>
    <div class="icon-description" style="margin:30px 0;font-size:24px;">論文や質問を投稿したり、コメントしたり、自分の質問、論文にコメントをもらおう</div>
    <%= image_tag 'post.gif',style: :"width:auto;height:400px"%>
  </div>
  
  <div class="col-md-12" style="text-align:center">
    <i class="fa fa-envelope-open-o icon-large" aria-hidden="true" style="margin:30px 0;font-size:24px;color:#00B0BC"></i>
    <div class="icon-title" style="margin:30px 0; font-size:48px; color:#00B0BC">Connect</div>
     <div class="icon-description"  style="margin:30px 0;font-size:24px;">プロフィールを充実させて、興味のある人につながろう</div>
       
     <%= image_tag 'curiocityimage.png',style: :"width:auto;height:400px"%>
      <div><a href="/auth/facebook" class="login-button" style="color:#ffffff">Facebookから今すぐログインする</a></div>

  </div>
  
</div>   <!-- 3つの特徴 -->
 
</div>
  
  
  
  
  
  
</div>

app/views/static_pages/profile.html.erb
<div class="row">
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" style="text-align:center;font-size:40px" id="user_profile">運営情報</div>
   <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile">
    
    <div class="profile-header">運営者</div>
    <div style="padding:20px">
        ICU 17 <a href ="www.twitter.com/kkdmgs110">DAI</a>
    </div>
    
    <div class="profile-header">URL</div>
    <div style="padding:20px">
        <a href ="www.criocity.com">www.curiocity.tech</a>
    </div>
    
    <div class="profile-header">お問合せ</div>
    <div style="padding:20px">
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSegW7qB3SaCLrFXyTzBjJPXC3bAqi6XPMkwgFFspXRWIKTgWQ/viewform?embedded=true" width="100%" height="400px" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます...</iframe>
    </div>
    
    <div class="profile-header">利用規約</div>
    <div style="padding:20px">
        <%= link_to "こちらを参照ください",terms_path %>
    </div>




    </div>
</div>

app/views/static_pages/terms.html.erb
<div class="row">
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" style="text-align:center;font-size:40px" id="user_profile">利用規約</div>
   <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile">
        <div style="padding:20px">
            この利用規約（以下，「本規約」といいます。）は，CurioCity（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
        </div>
    <div class="profile-header">第1条（適用)</div>
        <div style="padding:20px">
            本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。
        </div>
    
    <div class="profile-header">第2条（利用登録）</div>
        <div style="padding:20px">
            - 登録希望者が当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</br>
            - 当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</br>
              - （1）利用登録の申請に際して虚偽の事項を届け出た場合</br>
              - （2）本規約に違反したことがある者からの申請である場合</br>
              - （3）未成年者，成年被後見人，被保佐人または被補助人のいずれかであり，法定代理人，後見人，保佐人または補助人の同意等を得ていなかった場合</br>
              - （4）反社会的勢力等（暴力団，暴力団員，右翼団体，反社会的勢力，その他これに準ずる者を意味します。）である，または資金提供その他を通じて反社会的勢力等の維持，運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると当社が判断した場合</br>
              - （5）その他，当社が利用登録を相当でないと判断した場合</br>
        </div>    

    <div class="profile-header">第3条（ユーザーIDおよびパスワードの管理）</div>
        <div style="padding:20px">
            - ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。</br>
            - ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</br>
        </div>    

    <div class="profile-header">第4条（利用料金および支払方法）</div>
        <div style="padding:20px">
            - ユーザーは，本サービス利用の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。</br>
            - ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。</br>
        </div>    

    <div class="profile-header">第5条（禁止事項）</div>
        <div style="padding:20px">
            ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</br>
        - （1）法令または公序良俗に違反する行為</br>
        - （2）犯罪行為に関連する行為</br>
        - （3）当社のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</br>
        - （4）当社のサービスの運営を妨害するおそれのある行為</br>
        - （5）他のユーザーに関する個人情報等を収集または蓄積する行為</br>
        - （6）他のユーザーに成りすます行為</br>
        - （7）当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</br>
        - （8）当社，本サービスの他の利用者または第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</br>
        - （9）過度に暴力的な表現，露骨な性的表現，人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現，自殺，自傷行為，薬物乱用を誘引または助長する表現，その他反社会的な内容を含み他人に不快感を与える表現を，投稿または送信する行為</br>
        - （10）営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。），性行為やわいせつな行為を目的とする行為，面識のない異性との出会いや交際を目的とする行為，他のお客様に対する嫌がらせや誹謗中傷を目的とする行為，その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</br>
        - （11）宗教活動または宗教団体への勧誘行為</br>
        - （12）その他，当社が不適切と判断する行為</br>
        </div>    

    <div class="profile-header">第6条（本サービスの提供の停止等）</div>
        <div style="padding:20px">
        　- 当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</br>
          - （1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</br>
          - （2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</br>
          - （3）コンピュータまたは通信回線等が事故により停止した場合</br>
         </div>

    <div class="profile-header">第7条（著作権）</div>
        <div style="padding:20px"> 
            - ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報のみ，本サービスを利用し，投稿または編集することができるものとします。</br>
            - ユーザーが本サービスを利用して投稿または編集した文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿または編集された文章，画像，映像等を利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。</br>
            - 前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</br>
        </div>    

    <div class="profile-header">第8条（利用制限および登録抹消)</div>
        <div style="padding:20px"> 
              - 当社は，以下の場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</br>
              - （1）本規約のいずれかの条項に違反した場合</br>
              - （2）登録事項に虚偽の事実があることが判明した場合</br>
              - （3）破産，民事再生，会社更生または特別清算の手続開始決定等の申立がなされたとき</br>
              - （4）1年間以上本サービスの利用がない場合</br>
              - （5）当社からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合</br>
              - （6）第2条第2項各号に該当する場合</br>
              - （7）その他，当社が本サービスの利用を適当でないと判断した場合</br>
            - 前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。</br>
            - 当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</br>
        </div>    
    
    <div class="profile-header">第9条（保証の否認および免責事項）</div>
        <div style="padding:20px">
                - 当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</br>
                - 当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。</br>
                - 前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</br>
                - 当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</br>
        </div>    



    <div class="profile-header">第10条（サービス内容の変更等）</div>
        <div style="padding:20px">
                当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。
        </div>    

    <div class="profile-header">第11条（利用規約の変更）</div>
        <div style="padding:20px">
            当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。
        </div>    

    <div class="profile-header">第12条（通知または連絡）</div>
        <div style="padding:20px">
            ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。
        </div>    
    <div class="profile-header">第13条（権利義務の譲渡の禁止）</div>
        <div style="padding:20px">
                ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
        </div>    

    
    <div class="profile-header">第14条（準拠法・裁判管轄）</div>
        <div style="padding:20px">
                - 本規約の解釈にあたっては，日本法を準拠法とします。</br>
                - 本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。</br>
        </div>    
    </div>
</div>