config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comments
resources :follows
resources :forums
resources :posts
resources :static_pages
resources :users

    root to: "comments#index"
  end

  get 'forums/index'

  get 'forums/show'

  get 'forums/new'

  get 'forums/edit'

  mount Ckeditor::Engine => '/ckeditor'

  
  root "static_pages#home"
  get 'profile', to: "static_pages#profile"
  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"
  get 'major', to: "users#major",as: :major
  get 'terms', to: "static_pages#terms"
  get 'papermajor', to: "posts#papermajor"
  get 'forummajor', to: "forums#forummajor"
  get 'dashboard', to:"static_pages#dashboard"
  get 'auth/facebook', as: "login"
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'logout'   => 'sessions#destroy', as: "logout"
  
  get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"
  
  
  resources :users do
    resources :upvotes, only: :create
    resources :downvotes, only: :create
    resources :comments
  end
  
  resources :users do
  member do
    get 'clip', to: "users#clip"
    get 'show_pdf', to: "users#show_pdf" 
    get :follow
    post :follow
    get :unfollow
    get 'friends', to: "users#friends"
    post 'friends', to: "users#friends"
    put "like", to: "users#upvote"
    put "dislike", to: "users#downvote"
        end
  end
  
  resources :posts do
  resources :comments
  end
  
  resources :posts do 
    member do
      get 'like', to: "posts#like"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :forums do 
    member do
      get 'like', to: "forums#like"
      put "like", to: "forums#upvote"
      put "dislike", to: "forums#downvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :forums do
  resources :comments
  end
  
end

app/models/forum.rb
class Forum < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    acts_as_votable
    acts_as_taggable_on :labels # post.label_list が追加される
    acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
    acts_as_ordered_taggable_on :keyword
      
end

app/controllers/admin/forums_controller.rb
module Admin
  class ForumsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Forum.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Forum.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

before_action :authenticate_user
before_action :set_profile, except: [:edit,:update]
before_action :set_pending

    
    def index 
     @forums = Forum.all.order("created_at DESC")
    end
    
    def new 
        @forums = Forum.new
    end
   
    def create
        @forums = current_user.forums.create(forum_params)
        @users = User.where(major: @forums.major)
        puts @forums.major
        if @forums.valid?
            redirect_to forums_path
        else
            redirect_to :back
        end
    end
   
    
    def show
        @forums = Forum.find(params[:id])
    end
    
   def edit
        @forums = Forum.find(params[:id])
   end
   
   def update
      @forums = Forum.find(params[:id])
      @forums.update(forum_params)
      if @forums.valid?
        redirect_to @forums, notice: :"ディスカッションを変更しました"
      else
        render :edit, status: :unprocessable_entity
      end
   end
   
   def destroy
    @forum = Forum.find(params[:id])
    @forum.destroy
    redirect_to forums_path
   end
   
   def upvote
    @forums = Forum.find(params[:id])
    @forums.liked_by current_user
    redirect_to @forums
    end
    
    def downvote
      @forums = Forum.find(params[:id])
      @forums.unliked_by current_user
      redirect_to @forums
    end
    
    def forummajor
    @forums = Forum.where(major: params[:major]).order("created_at DESC")
    end
    
   
   
   # act as votable 
    def authenticate_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        unless current_user.present?
          redirect_to root_path,notice: "ログインしてください"
        end
  end
  
    
  def set_profile
    @user = current_user
    unless @user.username.present?
      flash[:notice] = 'プロフィールを編集すると、質問やコメントができるようになります。'
    end
  end
    
private

def forum_params
  params.require(:forum).permit(:content, :user_id, :title, :major)
end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/edit.html.erb
<% provide(:title, "質問をする") %>
<div class="row" style="padding-top:100px">  
   <%= form_for(@forums, :html => {:class => "form"}) do |f| %>
   <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
        
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>質問タイトル</div>
                <div style="padding:20px"><%= f.text_area :title, style: :"width:100%", placeholder: :"学問のこと、授業のことなど、質問してください。" %></div>
            </div>
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>質問に関係する専攻</div>
                <div style="padding:20px">
                      <%= f.select :major,([
                [""],
                ["アメリカ研究"],
                ["文化人類学"],
                ["アジア研究"],
                ["生物学"],
                ["経営学"],
                ["化学"],
                ["教育学"],
                ["経済学"],
                ["環境学"],
                ["グローバル研究"],
                ["ジェンダー・セクシャリティー研究"],
                ["歴史学"],
                ["国際関係学"],
                ["情報科学"],
                ["日本研究"],
                ["法学"],
                ["言語教育"],
                ["文学"],
                ["言語学"],
                ["メディア・コミュニケーション・文化"],
                ["数学"],
                ["音楽"],
                ["平和研究"],
                ["哲学・宗教学"],
                ["物理学"],
                ["政治学"],
                ["公共政策"],
                ["心理学"],
                ["社会学"],
                ["その他"]
                ]) %>
                </div>
            </div>
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>質問内容</div>
                <div style="padding:20px">  <%= f.cktext_area :content%></div>
            </div>

             <%= f.submit '質問する', class: :"btn btn-info btn-block" %>
            <% end %>
    </div>
 </div>

app/views/forums/forummajor.html.erb
<% provide(:title, "最新のディスカッション一覧") %>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa">最新のディスカッション(<%= @forums.count %>)</div>
    </div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<% @forums.each do |forum| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class="profile-header"><%= link_to forum.title, forum_path(forum)%> <small> /<%= time_ago_in_words(forum.created_at)%>前</small></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= forum.major %></div>
              <% if forum.user == current_user %>
                  <%= link_to "編集する", edit_forum_path(forum), class: :"button-radius" %>
                  <%= link_to "消去する", forum_path(forum), method: :delete, class: :"button-radius" %>
              <% end %>
    </div>
    <% end %>
    
</div>

app/views/forums/index.html.erb
<% provide(:title, "最新の質問一覧") %>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa">最新の質問一覧(<%= @forums.count %>)</div>
    </div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<% @forums.each do |forum| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class="profile-header"><%= link_to forum.title, forum_path(forum)%> <small> /<%= time_ago_in_words(forum.created_at)%>前</small></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><span class="tag-button"><%= forum.major %></span></div>
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>(<%= forum.votes_for.size %>) <i class="fa fa-comment" aria-hidden="true"></i>(<%= forum.comments.count %>)</div>
              <% if forum.user == current_user %>
                  <%= link_to "編集する", edit_forum_path(forum), class: :"button-radius" %>
                  <%= link_to "消去する", forum_path(forum), method: :delete, class: :"button-radius" %>
              <% end %>
    </div>
    <% end %>
    
</div>

app/views/forums/new.html.erb
<% provide(:title, "質問をする") %>
<div class="row" style="padding-top:100px">  
   <%= form_for(@forums, :html => {:class => "form"}) do |f| %>
   <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
        
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>質問タイトル</div>
                <div style="padding:20px"><%= f.text_area :title, style: :"width:100%", placeholder: :"学問のこと、授業のことなど、質問してください。" %></div>
            </div>
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>質問に関係する専攻</div>
                <div style="padding:20px">
                      <%= f.select :major,([
                [""],
                ["アメリカ研究"],
                ["文化人類学"],
                ["アジア研究"],
                ["生物学"],
                ["経営学"],
                ["化学"],
                ["教育学"],
                ["経済学"],
                ["環境学"],
                ["グローバル研究"],
                ["ジェンダー・セクシャリティー研究"],
                ["歴史学"],
                ["国際関係学"],
                ["情報科学"],
                ["日本研究"],
                ["法学"],
                ["言語教育"],
                ["文学"],
                ["言語学"],
                ["メディア・コミュニケーション・文化"],
                ["数学"],
                ["音楽"],
                ["平和研究"],
                ["哲学・宗教学"],
                ["物理学"],
                ["政治学"],
                ["公共政策"],
                ["心理学"],
                ["社会学"],
                ["その他"]
                ]) %>
                </div>
            </div>
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>質問内容</div>
                <div style="padding:20px">  <%= f.cktext_area :content%></div>
            </div>

             <%= f.submit '質問する', class: :"btn btn-info btn-block" %>
            <% end %>
    </div>
 </div>

app/views/forums/show.html.erb
<% provide(:title, "#{@forums.title}") %>

<div class="row">
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile" style="margin-top:50px">
          <%= link_to "フォーラム",forums_path %> / <span class="tag-button"><%= @forums.major %></span><%= link_to @forums.title, forum_path(@forums) %>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class=" profile-header"><%= link_to @forums.title, forum_path(@forums)%></div>
                <div class ="profile-left"><i class="fa fa-question-circle-o" aria-hidden="true"></i> <span class="tag-button"><%= @forums.major %></span></div>
                <div class ="profile-left"><%= link_to user_path(@forums.user) do%><%= image_tag @forums.user.attachment, :size =>"30x30" %><%= @forums.user.username %><% end %><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><span class="tag-button"><%= @forums.user.major%></span></div>
                <div class="profile-left"><i class="fa fa-info-circle" aria-hidden="true"></i> 質問内容</div>
                <div class="profile-left"><%= raw @forums.content %></div>
                <div class="profile-left">
                    <a href="#comment-form"><i class="fa fa-comment fa-2x colored-star"></i><%= @forums.comments.count %></a> 
                    <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-hashtags="CurioCity">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    <% unless current_user.voted_for? @forums %>
                        <%= link_to like_forum_path(@forums), method: :put do%><i class="fa fa-star-o fa-2x colored-star" aria-hidden="true"></i><%end%> <%= @forums.votes_for.size %>
                    <% else %>
                        <%= link_to dislike_forum_path(@forums), method: :put do%><i class="fa fa-star fa-2x colored-star" aria-hidden="true"></i><%end%> <%= @forums.votes_for.size %>
                    <% end %>
                    
                </div>
                <div>
                      <% if @forums.user == current_user %>
                        <%= link_to "編集する", edit_forum_path(@forums), class: :"button-radius" %>
                        <%= link_to "消去する", forum_path(@forums), method: :delete, class: :"button-radius" %>
                    <% end %>
                </div>
        </div>
              

<!------------------------------------------------------------------------------------------------------------->

<% if @forums.comments.present?%>
<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" style="text-align:center; font-size:24px">コメント(<%= @forums.comments.count %>)</div>
<!-- 表示comment ----------------------->  
  <% @forums.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="comment-content"> 
      <div class="col-md-2">
        <div><%= link_to user_path(comment.user) do %> <%= image_tag comment.user.attachment, :size =>"30x30" %><%= comment.user.username%>さん<%end%></div>
        <div><span class="tag-button"><%=comment.user.major%></span></div>
      </div>
      
      <div class="col-md-10">
          <%= comment.text.html_safe %>
        <div><small><%= time_ago_in_words(comment.created_at)%>前</small>
        <% unless current_user.voted_for? comment %>
          <%= link_to like_comment_path(comment), method: :put do%><i class="fa fa-star-o  fa-2x colored-star" aria-hidden="true"></i><% end %> <%= comment.votes_for.size %>
        <% else %>
          <%= link_to dislike_comment_path(comment), method: :put do%><i class="fa fa-star fa-2x uncolored-star" aria-hidden="true"></i><%end%> <%= comment.votes_for.size %>
        <% end %>
          <% if comment.user == current_user %>
            <%= link_to 'コメントを消す', forum_comment_path(forum_id: @forums.id, id: comment.id), method: :delete, class: :"tag-button" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<!--コメントを入力する -->  

<%= form_for Comment.new, url: forum_comments_path(@forums), method: :forum do |f| %>
<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile" style="text-align:center">コメントする</div>
  <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile"> 
    <%= f.cktext_area :text%>
    <div class="profile-left">
        <div><%= f.submit 'コメントする', class: :"btn btn-primary" %></div>
    </div>

</div>  
<% end %>

</div>