config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comments
resources :follows
resources :forums
resources :posts
resources :static_pages
resources :users

    root to: "comments#index"
  end

  get 'forums/index'

  get 'forums/show'

  get 'forums/new'

  get 'forums/edit'

  mount Ckeditor::Engine => '/ckeditor'

  
  root "static_pages#home"
  get 'profile', to: "static_pages#profile"
  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"
  get 'major', to: "users#major",as: :major
  get 'terms', to: "static_pages#terms"
  get 'papermajor', to: "posts#papermajor"
  get 'forummajor', to: "forums#forummajor"
  get 'dashboard', to:"static_pages#dashboard"
  get 'auth/facebook', as: "login"
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'logout'   => 'sessions#destroy', as: "logout"
  
  get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"
  
  
  resources :users do
    resources :upvotes, only: :create
    resources :downvotes, only: :create
    resources :comments
  end
  
  resources :users do
  member do
    get 'clip', to: "users#clip"
    get 'show_pdf', to: "users#show_pdf" 
    get :follow
    post :follow
    get :unfollow
    get 'friends', to: "users#friends"
    post 'friends', to: "users#friends"
    put "like", to: "users#upvote"
    put "dislike", to: "users#downvote"
        end
  end
  
  resources :posts do
  resources :comments
  end
  
  resources :posts do 
    member do
      get 'like', to: "posts#like"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :forums do 
    member do
      get 'like', to: "forums#like"
      put "like", to: "forums#upvote"
      put "dislike", to: "forums#downvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :forums do
  resources :comments
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :comments
  has_many :posts
  has_many :forums

  acts_as_votable
  acts_as_taggable_on :labels # post.label_list が追加される
  acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
  acts_as_ordered_taggable_on :interests
  #http://ruby-rails.hatenadiary.com/entry/20150225/1424858414
  
  #ポリもーふぃずむがわかんないからgem頼り
  
  acts_as_voter
  acts_as_votable
  
  acts_as_followable
  acts_as_follower
  
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  
  # Initializes or updates user object when logging in with Facebook
  
  def self.from_omniauth(auth)
    where(fb_id: auth.uid).first_or_create do |user|
      user.oauth_provider = auth.provider
      user.fb_id = auth.uid
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.name ||= auth.info.name
      user.avatar_url ||= "http://graph.facebook.com/#{auth.uid}/picture?width=500"
      user.save!
    end
  end
  
  def facebook #koalaのtutorial参考
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end
  
  def friends
   @friends = facebook.get_connections("me", "friends")
  end
  
  validates :username,     length: { maximum: 40 }        # 値が「2文字以上」であれば有効
  validates :bio,      length: { maximum: 1000 }
  validates :abstract,      length: { maximum: 1000 }# 値が「500文字以下」であらば有効
end

  
  

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user
before_action :correct_user, only: [:edit, :update]
before_action :set_pending

  def authenticate_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        unless current_user.present?
          redirect_to root_path,notice: "ログインしてください"
        end
  end
  
  def index
    @users = User.all.order("created_at desc")
    case
      when current_user.username.nil?
        then flash[:notice] = "プロフィールを編集しましょう。メールアドレスを入力すると、コンタクト申請を送れるようになります"
      when current_user.email.nil?
        then flash[:notice] = "気になった人にコンタクトをとってみませんか？メールアドレスを登録すると、コンタクトリクエストが送信できます"
    end
  end
  
  def show
    #@user = User.find(params[:id])
   @user = User.find(params[:id])
   @posts = @user.posts.all.order("created_at DESC")
   @comments = @user.comments.all.order("created_at DESC")
   @comment  = @user.comments.build(user_id: current_user.id) 
    unless current_user.name.present? || current_user.bio.present?
    flash[:notice] = "プロフィールから、名前とプロフィール、連絡先を記入すると、#{@user.username}さんと連絡先が交換できます"
    end
  end
  
  def new 
    @user = User.find(params[:id])
    
  end
  
  def create
    @user = User.create(params[:id])
    @user = current_user.follow(@user)
    redirect_to users_path
  end
  
  def edit
    @user = User.find(params[:id])
  end  
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to dashboard_path
    else
      render 'edit',notice:'#{current_user.username}さんのプロフィールを編集しました'
    end
  end
  
  def clip
    @user = current_user.votes.up.for_type(User).votables
  end
  
  def friends
   @users = User.find(params[:id])
   @current_user = current_user
   @current_user_following = current_user.all_following 
   @current_user_followers = current_user.followers
   @following = @users.all_following
   @followers = @users.followers
   @mutualfriends = @following & @followers
   @pendingfriends = @followers - @following
   @sendingfriends = @following - @followers
   @currentuser_sending = @current_user_following-@current_user_followers
   #@accept = current_user.accept_request(@user)
  end
  
  def follow
    @user = User.find(params[:id])
    if current_user
      if current_user == @user　
        flash[:notice] = "自分自身をフォローできません。"
        redirect_to :back
      else
        current_user.follow(@user)
        RequestMailer.send_email(@user,current_user).deliver_now
        #RequestMailer.send_email(@user,current_user,@message).deliver_now こうすれば理論上届くようになる
        flash[:notice] = "#{@user.username}さんにコンタクトリクエストを送りました。"
        redirect_to :back
      end
    else
      redirect_to :back
    end
  end

  def unfollow
    @user = User.find(params[:id])
    if current_user
      current_user.stop_following(@user)
      redirect_to users_path,notice:"#{@user.username}さんへのコンタクトを取り消しました。"
    else
      flash[:error] = "You must <a href='/users/sign_in'>login</a> to unfollow #{@user.name}.".html_safe
      redirect_to users_path
    end
  end
  
  def upvote
    @user = User.find(params[:id])
    @user.upvote_by current_user
    redirect_to users_path,notice: "#{@user.username}さんの論文をクリップしました。"
  end
  
  def downvote
    @user = User.find(params[:id])
    @user.downvote_by current_user
    redirect_to users_path,notice:"#{@user.username}さんの論文からクリップを外しました"
  end
  
  def major
    @users = User.where(major: params[:major])
  end
  
  def set_profile
    @user = current_user
    unless @user.username.present?
      redirect_to edit_user_path(current_user),notice: 'プロフィールを編集しましょう！(あとで変更することができます)'
    end
    
  end
   
 private
  
    def correct_user
      # .to_i converts values to integers here because params[:id] is a string
      # Without this current_user.id and params[:id] would never match
      if current_user.id != params[:id].to_i
        redirect_to root_url
      end
    end
    
    def user_params
      params.require(:user).permit(:bio, :abstract, :thesisName, :attachment, :major, :username, :graduate, :email, :interest_list, :years, :twitter_id,:people)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/clip.html.erb
<% provide(:title, "お気に入り") %>
<div class="row">


  
</div

<div class="row" >
<% @users.each do |user| %>
    <% unless user.username.nil? %>
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12  profile-header"><span class="glyphicon glyphicon glyphicon-user fa-2x" aria-hidden="true"></span> <%= link_to user.username, user_path(user) %></div>
          <div class="col-xs-12 col-sm-12 col-md-12" > <!-- ユーザーの属性 -->
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= user.major %></div>
            <% if user.thesisName.present? %>
            <div class="profile-left">
                <div><i class="fa fa-info-circle" aria-hidden="true"></i><%= user.thesisName %></div>
            </div>
            <% end %>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                <% user.interest_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                <% end %>
            <% if user.attachment.present? %>
                <div class="profile-left pdf-button-small"><i class="fa fa-paperclip" aria-hidden="true"></i><%= link_to asset_path(user.attachment) do %>PDFを見る<% end %></div>
            <% else %>
                <p>このユーザーはまだ論文をアップロードしていません</p>
                
            <% end %>
            <!--- USERがPDFを持っていたら、PDFへのリンクをはる -->
        
          </div>
         </div>
    <% end %>
<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>



<div class="row">
    <div class="row mobile-show">
      <div class="col-xs-12" id="user_profile">
        <div class="profile-header">メジャー別ユーザー</div>
        <span class="tag-button"><%= link_to "アメリカ研究 (#{User.where(major: "アメリカ研究").count})", major_path(major: "アメリカ研究") %></span>
        <span class="tag-button"><%= link_to "教育学(#{User.where(major: "教育学").count})", major_path(major: "教育学") %></span>
        <span class="tag-button"><%= link_to "文化人類学(#{User.where(major: "文化人類学").count})", major_path(major: "文化人類学") %></span>
        <span class="tag-button"><%= link_to "アジア研究(#{User.where(major: "アジア研究").count})", major_path(major: "アジア研究") %></span>
        <span class="tag-button"><%= link_to "生物学(#{User.where(major: "生物学").count})", major_path(major: "生物学") %></span>
        <span class="tag-button"><%= link_to "経営学(#{User.where(major: "経営学").count})", major_path(major: "経営学") %></span>
        <span class="tag-button"><%= link_to "化学(#{User.where(major: "化学").count})", major_path(major: "化学") %></span>
        <span class="tag-button"><%= link_to "経済学(#{User.where(major: "経済学").count})", major_path(major: "経済学") %></span>
        <span class="tag-button"><%= link_to "環境学(#{User.where(major: "環境学").count})", major_path(major: "環境学") %></span>
        <span class="tag-button"><%= link_to "グローバル研究(#{User.where(major: "グローバル研究").count})", major_path(major: "グローバル研究") %></span>
        <span class="tag-button"><%= link_to "ジェンダー・セクシャリティー研究(#{User.where(major: "ジェンダー・セクシャリティー研究").count})", major_path(major: "ジェンダー・セクシャリティー研究") %></span>
        <span class="tag-button"><%= link_to "歴史学(#{User.where(major: "歴史学").count})", major_path(major: "歴史学") %></span>
        <span class="tag-button"><%= link_to "国際関係学(#{User.where(major: "国際関係学").count})", major_path(major: "国際関係学") %></span>
        <span class="tag-button"><%= link_to "情報科学(#{User.where(major: "情報科学").count})", major_path(major: "情報科学 ") %></span>
        <span class="tag-button"><%= link_to "日本研究(#{User.where(major: "日本研究").count})", major_path(major: "日本研究") %></span>
        <span class="tag-button"><%= link_to "文学(#{User.where(major: "文学").count})", major_path(major: "文学") %></span>
        <span class="tag-button"><%= link_to "言語学(#{User.where(major: "言語学").count})", major_path(major: "言語学") %></span>
        <span class="tag-button"><%= link_to "メディア・コミュニケーション・文化(#{User.where(major: "メディア・コミュニケーション・文化").count})", major_path(major: "メディア・コミュニケーション・文化") %></span>
        <span class="tag-button"><%= link_to "数学(#{User.where(major: "数学").count})", major_path(major: "数学") %></span>
        <span class="tag-button"><%= link_to "音楽(#{User.where(major: "音楽").count})", major_path(major: "音楽") %></span>
        <span class="tag-button"><%= link_to "哲学・宗教学(#{Post.where(major: "哲学・宗教学").count})", papermajor_path(major: "哲学・宗教学") %></span>
        <span class="tag-button"><%= link_to "物理学(#{Post.where(major: "物理学").count})", papermajor_path(major: "物理学") %></span>
        <span class="tag-button"><%= link_to "政治学(#{Post.where(major: "政治学").count})", papermajor_path(major: "政治学") %></span>
        <span class="tag-button"><%= link_to "公共政策(#{Post.where(major: "公共政策").count})", papermajor_path(major: "公共政策") %></span>
        <span class="tag-button"><%= link_to "心理学(#{Post.where(major: "心理学").count})", papermajor_path(major: "心理学") %></span>
        <span class="tag-button"><%= link_to "社会学(#{Post.where(major: "社会学").count})", papermajor_path(major: "社会学") %></span>
        <span class="tag-button"><%= link_to "その他(#{Post.where(major: "その他").count})", papermajor_path(major: "その他") %></span>
    </div>
  </div>
    
    <% @users.each do |user| %>
    <% unless user.username.nil? %>
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12  profile-header">
          <% if user.attachment.present? %>
            <%= image_tag user.attachment, :size =>"30x30" %><%= link_to user.username, user_path(user)%>
          <% else %>
            <%= image_tag "twitteregg.png", :size =>"30x30" %><%= link_to user.username, user_path(user)%>
          <% end %>
        </div>
          <div class="col-xs-12 col-sm-12 col-md-12" > <!-- ユーザーの属性 -->
            <div class="profile-left"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= user.years %></div>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= user.major %></div>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                <% user.interest_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                <% end %>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> 論文(<%= user.posts.count %>)</div>
            <% if user.posts.present? %>
                <% user.posts.each do |post| %>
                <div class="profile-left" id="posts-content">
                  <div>
                    <i class="fa fa-sticky-note-o" aria-hidden="true"></i> <%= link_to post.title, post_path(post) %>
                    <i class="fa fa-comment-o" aria-hidden="true"></i> <%= post.comments.count %> <i class="fa fa-heart-o" aria-hidden="true"></i> <%= post.votes_for.size %>
                  </div>
                  <div><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %>
                    <% post.keyword_list.each do |tag| %>
                      <span class="tag-button"><%= tag %></span>
                    <% end %>
                  </div>
                </div>
                <% end %>
            </div>
            <% end %>
            
            <!--- USERがPDFを持っていたら、PDFへのリンクをはる -->
        
          </div>
         </div>
    <% end %>
    <% end %>
</div><!-- row ----------------------------->

app/views/users/major.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0"><%= link_to "ユーザー一覧",users_path %> / <%= params[:major] %> (<%= @users.count %>)</div>
        <span>
        <% @users.each do |user| %>
            <%= link_to user_path(user) do %><%= image_tag user.attachment, :size =>"50x50" %> <% end %>
        <% end %>
        </span>
    </div>
    
    <div class="row mobile-show">
      <div class="col-xs-12" id="user_profile">
        <div class="profile-header">メジャー別ユーザー</div>
        <span class="tag-button"><%= link_to "アメリカ研究 (#{User.where(major: "アメリカ研究").count})", major_path(major: "アメリカ研究") %></span>
        <span class="tag-button"><%= link_to "教育学(#{User.where(major: "教育学").count})", major_path(major: "教育学") %></span>
        <span class="tag-button"><%= link_to "文化人類学(#{User.where(major: "文化人類学").count})", major_path(major: "文化人類学") %></span>
        <span class="tag-button"><%= link_to "アジア研究(#{User.where(major: "アジア研究").count})", major_path(major: "アジア研究") %></span>
        <span class="tag-button"><%= link_to "生物学(#{User.where(major: "生物学").count})", major_path(major: "生物学") %></span>
        <span class="tag-button"><%= link_to "経営学(#{User.where(major: "経営学").count})", major_path(major: "経営学") %></span>
        <span class="tag-button"><%= link_to "化学(#{User.where(major: "化学").count})", major_path(major: "化学") %></span>
        <span class="tag-button"><%= link_to "経済学(#{User.where(major: "経済学").count})", major_path(major: "経済学") %></span>
        <span class="tag-button"><%= link_to "環境学(#{User.where(major: "環境学").count})", major_path(major: "環境学") %></span>
        <span class="tag-button"><%= link_to "グローバル研究(#{User.where(major: "グローバル研究").count})", major_path(major: "グローバル研究") %></span>
        <span class="tag-button"><%= link_to "ジェンダー・セクシャリティー研究(#{User.where(major: "ジェンダー・セクシャリティー研究").count})", major_path(major: "ジェンダー・セクシャリティー研究") %></span>
        <span class="tag-button"><%= link_to "歴史学(#{User.where(major: "歴史学").count})", major_path(major: "歴史学") %></span>
        <span class="tag-button"><%= link_to "国際関係学(#{User.where(major: "国際関係学").count})", major_path(major: "国際関係学") %></span>
        <span class="tag-button"><%= link_to "情報科学(#{User.where(major: "情報科学").count})", major_path(major: "情報科学 ") %></span>
        <span class="tag-button"><%= link_to "日本研究(#{User.where(major: "日本研究").count})", major_path(major: "日本研究") %></span>
        <span class="tag-button"><%= link_to "文学(#{User.where(major: "文学").count})", major_path(major: "文学") %></span>
        <span class="tag-button"><%= link_to "言語学(#{User.where(major: "言語学").count})", major_path(major: "言語学") %></span>
        <span class="tag-button"><%= link_to "メディア・コミュニケーション・文化(#{User.where(major: "メディア・コミュニケーション・文化").count})", major_path(major: "メディア・コミュニケーション・文化") %></span>
        <span class="tag-button"><%= link_to "数学(#{User.where(major: "数学").count})", major_path(major: "数学") %></span>
        <span class="tag-button"><%= link_to "音楽(#{User.where(major: "音楽").count})", major_path(major: "音楽") %></span>
        <span class="tag-button"><%= link_to "哲学・宗教学(#{Post.where(major: "哲学・宗教学").count})", papermajor_path(major: "哲学・宗教学") %></span>
        <span class="tag-button"><%= link_to "物理学(#{Post.where(major: "物理学").count})", papermajor_path(major: "物理学") %></span>
        <span class="tag-button"><%= link_to "政治学(#{Post.where(major: "政治学").count})", papermajor_path(major: "政治学") %></span>
        <span class="tag-button"><%= link_to "公共政策(#{Post.where(major: "公共政策").count})", papermajor_path(major: "公共政策") %></span>
        <span class="tag-button"><%= link_to "心理学(#{Post.where(major: "心理学").count})", papermajor_path(major: "心理学") %></span>
        <span class="tag-button"><%= link_to "社会学(#{Post.where(major: "社会学").count})", papermajor_path(major: "社会学") %></span>
        <span class="tag-button"><%= link_to "その他(#{Post.where(major: "その他").count})", papermajor_path(major: "その他") %></span>
    </div>
  </div>
    <% @users.each do |user| %>
    <% unless user.username.nil? %>
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12  profile-header"><%= image_tag user.attachment, :size =>"50x50" %><%= link_to user.username, user_path(user)%></div>
          <div class="col-xs-12 col-sm-12 col-md-12" > <!-- ユーザーの属性 -->
            <div class="profile-left"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= user.years %></div>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= user.major %></div>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                <% user.interest_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                <% end %>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> 論文(<%= user.posts.count %>)</div>
            <% if user.posts.present? %>
                <% user.posts.each do |post| %>
                <div class="profile-left" id="posts-content">
                  <div>
                    <i class="fa fa-sticky-note-o" aria-hidden="true"></i> <%= link_to post.title, post_path(post) %>
                    <i class="fa fa-comment-o" aria-hidden="true"></i> <%= post.comments.count %> <i class="fa fa-heart-o" aria-hidden="true"></i> <%= post.votes_for.size %>
                  </div>
                  <div><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %>
                    <% post.keyword_list.each do |tag| %>
                      <span class="tag-button"><%= tag %></span>
                    <% end %>
                  </div>
                </div>
                <% end %>
            </div>
            <% end %>
            
            <!--- USERがPDFを持っていたら、PDFへのリンクをはる -->
        
          </div>
         </div>
    <% end %>
    <% end %>
</div><!-- row ----------------------------->

app/views/users/show.html.erb
<% provide(:title, "#{@user.username}さん") %>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile">
         <%= link_to "ユーザー一覧",users_path %> / <%= image_tag @user.attachment, :size =>"30x30" %><%= link_to @user.username, user_path(@user) %>
    </div>
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12 profile-header">
            <%= image_tag @user.attachment, :size =>"50x50" %>
            <%= link_to @user.username, user_path(@user)%>
            <% if @user == current_user %>
             <%= link_to "編集", edit_user_path(current_user), class:"button-radius" %>
            <% end %>
        </div>
          <div class="col-sm-12 col-xs-12 col-md-12" > <!-- ユーザーの属性 -->
          <div class="profile-left"><i class="fa fa-graduation-cap" aria-hidden="true"></i> <%= @user.years %></div>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= @user.major %></div>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>　キーワード</div>
                <% @user.interest_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                <% end %>
          </div>
          
          
          <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>プロフィール</div>
                <div style="padding:20px"><%= @user.bio %></div>
            </div>
            
             <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>会ってみたい人</div>
                <div style="padding:20px"><%= @user.people %></div>
            </div>
            
            <% if current_user.email.present? & current_user.username.present? %>
            
                <% if @user.email.present?%> 
            <!-----------------フォローするユーザーにまだフォローしていない場合は、コンタクト申請を送る------------------------------>
                    <% if !(current_user.following?(@user)) %>
                        <div class="profile-left"><%= link_to " コンタクトリクエストを送る", follow_user_path(@user),:style =>"color:white;",class: :"request-button-small" %></div>
                    <% elsif current_user.following?(@user) && !(@user.following?(current_user))%>
                        <div class="profile-left request-button-small">コンタクトリクエストを申請中</div>
            <!-----------------フォローするユーザーへのコンタクト申請が済んでいるときはコンタクト可能と表示する------------------------------>
                    <% else %>
                        <span class="profile-left request-button-small"><i class="fa fa-user-plus" aria-hidden="true"></i>コンタクト可能</span>
                    <% end %>
            <!-----------------フォローするユーザーのメールアドレスが未登録の場合、メールアドレスが登録されていないと表示する------------------------------>
                <% else %>
                    <div class="profile-left"><i class="fa fa-user-plus" aria-hidden="true"></i>メールアドレスが登録されていません</div>
                <% end %>
              <!---------------------自分のメールアドレス、ユーザ名が存在しない場合、自分のプロフィールを編集するようにリンクを張る。 -------->
              <% else %>
                  <div class="profile-left request-button-small"><%= link_to 'コンタクトリクエストが送れるよう、自分のプロフィールを編集しましょう。', edit_user_path(current_user),:style => "color:white" %></div>
              <% end %>
            
            
          </div>
    </div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<% if @posts.present? %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" style="text-align:center; font-size:24px">論文(<%= @posts.count %>)</div>
    
    <% @posts.each do |post| %>
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="posts-index"> 
                <div class=" profile-header"><%= link_to post.title, post_path(post)%></div>
                <% post.keyword_list.each do |tag| %>
                    <span class="tag-button"><%= tag %></span>
                  <% end %>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %></div>
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i> (<%= post.votes_for.size %>) <i class="fa fa-comment" aria-hidden="true"></i>(<%= post.comments.count %>)</div>
                

              
                
              <% if post.user == current_user %>
                  <%= link_to "編集する", edit_post_path(post), class: :"button-radius" %>
                  <%= link_to "消去する", post_path(post), method: :delete, class: :"button-radius" %>
              <% end %>
              
           </div> 
            <% end %>
<% end %>
            <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile text-center" id="user_profile">
                 <%= link_to "ユーザー一覧",users_path %> / <%= image_tag @user.attachment, :size =>"30x30" %><%= link_to @user.username, user_path(@user) %>
            </div>

</div>