config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :comments
resources :follows
resources :forums
resources :posts
resources :static_pages
resources :users

    root to: "comments#index"
  end

  get 'forums/index'

  get 'forums/show'

  get 'forums/new'

  get 'forums/edit'

  mount Ckeditor::Engine => '/ckeditor'

  
  root "static_pages#home"
  get 'profile', to: "static_pages#profile"
  get 'users', to: "users#index", as: "users"
  get 'users/:id', to: "users#show", as: "user"
  get 'major', to: "users#major",as: :major
  get 'terms', to: "static_pages#terms"
  get 'papermajor', to: "posts#papermajor"
  get 'forummajor', to: "forums#forummajor"
  get 'dashboard', to:"static_pages#dashboard"
  get 'auth/facebook', as: "login"
  get 'auth/facebook/callback', to: 'sessions#create'
  get 'logout'   => 'sessions#destroy', as: "logout"
  
  get 'users/:id/edit', to: "users#edit", as: "edit_user"
  patch 'users/:id', to: "users#update"
  
  
  resources :users do
    resources :upvotes, only: :create
    resources :downvotes, only: :create
    resources :comments
  end
  
  resources :users do
  member do
    get 'clip', to: "users#clip"
    get 'show_pdf', to: "users#show_pdf" 
    get :follow
    post :follow
    get :unfollow
    get 'friends', to: "users#friends"
    post 'friends', to: "users#friends"
    put "like", to: "users#upvote"
    put "dislike", to: "users#downvote"
        end
  end
  
  resources :posts do
  resources :comments
  end
  
  resources :posts do 
    member do
      get 'like', to: "posts#like"
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end

  resources :forums do 
    member do
      get 'like', to: "forums#like"
      put "like", to: "forums#upvote"
      put "dislike", to: "forums#downvote"
    end
  end
  
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
  end
  
  resources :forums do
  resources :comments
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :file, AttachmentUploader
    acts_as_votable
    belongs_to :user
    has_many :comments, dependent: :destroy
    acts_as_taggable_on :labels # post.label_list が追加される
    acts_as_taggable            # acts_as_taggable_on :tags のエイリアス
    acts_as_ordered_taggable_on :keywords
    
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user
before_action :set_pending
before_action :set_profile

    
    def index 
     @posts = Post.all.order("created_at DESC")
    end
    
    def new 
        @posts = Post.new
    end
    
    def show
        @posts = Post.find(params[:id])
    end
    
    def create
        @post = current_user.posts.create(post_params)
        if @post.valid?
            redirect_to users_path
        else
            redirect_to :back
        end
    end
   
   def edit
        @post = Post.find(params[:id])
   end
   
   
   def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      if @post.valid?
        redirect_to @post, notice: :"論文を変更しました"
      else
        render :edit, status: :unprocessable_entity
      end
   end
   
   def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
   end
   
   # act as votable 
   
   def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    RequestMailer.like_email(@post.user,current_user).deliver_now
    redirect_to @post
    end
    
    def downvote
      @post = Post.find(params[:id])
      @post.unliked_by current_user
      redirect_to @post
    end
    
    def like
     @user = User.find(params[:id])
     @posts = @user.votes.up.for_type(Post).votables
    end
    
    def papermajor
    @posts = Post.where(major: params[:major]).order("created_at DESC")
    end
    
    def authenticate_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        unless current_user.present?
          redirect_to root_path,notice: "ログインしてください"
         end
    end
    
    def set_profile
        @user = current_user
        unless @user.username.present?
          flash[:notice] = 'プロフィールを編集すると、質問やコメントができるようになります。'
        end
    end
  
    
private

def post_params
  params.require(:post).permit(:user_id, :file, :summary, :title, :year, :teacher, :major, :keyword, :keyword_list, :agreement)
end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% provide(:title, "論文を編集") %>
<div class="row" style="padding-top:100px">  
    <div class="form-group">
        <%= form_for(@post, :html => {:class => "form"})do |f| %>
       <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
                <div class="profile-left">
                    <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>論文名</div>
                    <div style="padding:20px"><%= f.text_area :title, style: :"width:100%" %></div>
                </div>
                
                <div class="profile-left">
                    <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>分野</div>
                    <div style="padding:20px">
                          <%= f.select :major,([
                    ["アメリカ研究"],
                ["文化人類学"],
                ["アジア研究"],
                ["生物学"],
                ["経営学"],
                ["化学"],
                ["教育学"],
                ["経済学"],
                ["環境学"],
                ["グローバル研究"],
                ["ジェンダー・セクシャリティー研究"],
                ["歴史学"],
                ["国際関係学"],
                ["情報科学"],
                ["日本研究"],
                ["法学"],
                ["言語教育"],
                ["文学"],
                ["言語学"],
                ["メディア・コミュニケーション・文化"],
                ["数学"],
                ["音楽"],
                ["平和研究"],
                ["哲学・宗教学"],
                ["物理学"],
                ["政治学"],
                ["公共政策"],
                ["心理学"],
                ["社会学"],
                ["その他"]
                    ]) %>
                    </div>
                </div>
                
                    <div class="profile-left">
                        <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>分野</div>
                         <div><%= text_field_tag 'post[keyword_list]', @post.keyword_list.join(','), "data-role" => "tagsinput", :class =>"form" %></div>
                    </div>
                    
                <div class="profile-left">
                    <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>要約</div>
                    <div style="padding:20px"> <%= f.text_area :summary, style: :"width:100%"  %></div>
                </div>
        
                 <div class="profile-left">
                    <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>PDFを添付</div>
                    <div style="padding:20px"><%= f.file_field :file %></div>
                </div>
                 
                 <%= f.submit '変更する' %>
                <% end %>
        </div>
    </div>
 </div>

app/views/posts/index.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0; color:#aaaaaa">論文一覧(<%= @posts.count %>)</div>
    </div>
    
    <div class="col-xs-12 mobile-show" id="user_profile">
        <span class="tag-button"><%= link_to "アメリカ研究(#{Post.where(major: "アメリカ研究").count})", papermajor_path(major: "アメリカ研究") %></span>
        <span class="tag-button"><%= link_to "教育学(#{Post.where(major: "教育学").count})", papermajor_path(major: "教育学") %></span>
        <span class="tag-button"><%= link_to "文化人類学(#{Post.where(major: "文化人類学").count})", papermajor_path(major: "文化人類学") %></span>
        <span class="tag-button"><%= link_to "アジア研究(#{Post.where(major: "アジア研究").count})", papermajor_path(major: "アジア研究") %></span>
        <span class="tag-button"><%= link_to "生物学(#{Post.where(major: "生物学").count})", papermajor_path(major: "生物学") %></span>
        <span class="tag-button"><%= link_to "経営学(#{Post.where(major: "経営学").count})", papermajor_path(major: "経営学") %></span>
        <span class="tag-button"><%= link_to "化学(#{Post.where(major: "化学").count})", papermajor_path(major: "化学") %></span>
        <span class="tag-button"><%= link_to "経済学(#{Post.where(major: "経済学").count})", papermajor_path(major: "経済学") %></span>
        <span class="tag-button"><%= link_to "環境学(#{Post.where(major: "環境学").count})", papermajor_path(major: "環境学") %></span>
        <span class="tag-button"><%= link_to "グローバル研究(#{Post.where(major: "グローバル研究").count})", papermajor_path(major: "グローバル研究") %></span>
        <span class="tag-button"><%= link_to "ジェンダー・セクシャリティー研究(#{Post.where(major: "ジェンダー・セクシャリティー研究").count})", papermajor_path(major: "ジェンダー・セクシャリティー研究") %></span>
        <span class="tag-button"><%= link_to "歴史学(#{Post.where(major: "歴史学").count})", papermajor_path(major: "歴史学") %></span>
        <span class="tag-button"><%= link_to "国際関係学(#{Post.where(major: "国際関係学").count})", papermajor_path(major: "国際関係学") %></span>
        <span class="tag-button"><%= link_to "情報科学(#{Post.where(major: "情報科学").count})", papermajor_path(major: "情報科学 ") %></span>
        <span class="tag-button"><%= link_to "日本研究(#{Post.where(major: "日本研究").count})", papermajor_path(major: "日本研究") %></span>
        <span class="tag-button"><%= link_to "文学(#{Post.where(major: "文学").count})", papermajor_path(major: "文学") %></span>
        <span class="tag-button"><%= link_to "言語学(#{Post.where(major: "言語学").count})", papermajor_path(major: "言語学") %></span>
        <span class="tag-button"><%= link_to "メディア・コミュニケーション・文化(#{Post.where(major: "メディア・コミュニケーション・文化").count})", papermajor_path(major: "メディア・コミュニケーション・文化") %></span>
        <span class="tag-button"><%= link_to "数学(#{Post.where(major: "数学").count})", papermajor_path(major: "数学") %></span>
        <span class="tag-button"><%= link_to "音楽(#{Post.where(major: "音楽").count})", papermajor_path(major: "音楽") %></span>
        <span class="tag-button"><%= link_to "哲学・宗教学(#{Post.where(major: "哲学・宗教学").count})", papermajor_path(major: "哲学・宗教学") %></span>
        <span class="tag-button"><%= link_to "物理学(#{Post.where(major: "物理学").count})", papermajor_path(major: "物理学") %></span>
        <span class="tag-button"><%= link_to "政治学(#{Post.where(major: "政治学").count})", papermajor_path(major: "政治学") %></span>
        <span class="tag-button"><%= link_to "公共政策(#{Post.where(major: "公共政策").count})", papermajor_path(major: "公共政策") %></span>
        <span class="tag-button"><%= link_to "心理学(#{Post.where(major: "心理学").count})", papermajor_path(major: "心理学") %></span>
        <span class="tag-button"><%= link_to "社会学(#{Post.where(major: "社会学").count})", papermajor_path(major: "社会学") %></span>
        <span class="tag-button"><%= link_to "その他(#{Post.where(major: "その他").count})", papermajor_path(major: "その他") %></span>
    </div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<% @posts.each do |post| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class="profile-header"><%= link_to post.title, post_path(post)%> <small> /<%= time_ago_in_words(post.created_at)%>前</small></div>
                <div class="profile-left">
                    <% post.keyword_list.each do |tag| %>
                        <span class="tag-button"><%= tag %></span>
                    <% end %>
                </div>
                <div class ="profile-left"><%= image_tag post.user.attachment, :size =>"20x20" %> <%=link_to post.user.username,user_path(post.user)%></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %></div>
    
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>(<%= post.votes_for.size %>) <i class="fa fa-comment" aria-hidden="true"></i>(<%= post.comments.count %>)</div>

              <% if post.user == current_user %>
                  <%= link_to "編集する", edit_post_path(post), class: :"button-radius" %>
                  <%= link_to "消去する", post_path(post), method: :delete, class: :"button-radius" %>
              <% end %>
    </div>
    <% end %>
    
</div>

app/views/posts/like.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile">
         <%= link_to "ユーザー一覧",users_path %> / <%= image_tag @user.attachment, :size =>"30x30" %><%= link_to @user.username, user_path(@user) %>　/ お気に入りした論文
    </div>
    
    <% @posts.each do |post| %>
      <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> <!-- User Profile ----------------------------->
        <div class="col-xs-12 col-sm-12 col-md-12  profile-header"><%= link_to post_path(post.id) do%><%= post.title %><% end %></div>
          <div class="col-xs-12 col-sm-12 col-md-12" > <!-- ユーザーの属性 -->
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-user" aria-hidden="true"></span> <%= post.user.username %></div>
            <div class="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span> <%= post.major %></div>
            <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>キーワード</div>
            <span><%= post.keyword %></span>
            <div><%= post.summary %></div>
            <i class="fa fa-heart-o" aria-hidden="true"></i>(<%= post.votes_for.size %>)
            <i class="fa fa-comment-o" aria-hidden="true"></i>(<%= post.comments.count %>)
            <% if post.user == current_user %>
                <%= link_to '論文を編集する', edit_post_path(post.id) %>
                <%= link_to '論文を削除する', post_path(post.id), method: :delete %>
            <% end %> 
          </div>
         </div>
    <% end %>
</div><!-- row ----------------------------->

app/views/posts/new.html.erb
<% provide(:title, "論文を追加する") %>
<div class="row" style="padding-top:100px">  
   <%= form_for(@posts, :html => {:class => "form"}) do |f| %>
   <div class="col-xs-12 col-sm-12 col-md-12 col-xs-12" id="profile-abstract"> <!-- 論文/興味のabstract -->
        
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-heart" aria-hidden="true"></i>論文タイトル</div>
                <div style="padding:20px"><%= f.text_area :title, style: :"width:100%", placeholder: :"論文のタイトルを入力してください。（例）学校外教育について" %></div>
            </div>
            
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>専攻</div>
                <div style="padding:20px">
                      <%= f.select :major,([
                [""],
                ["アメリカ研究"],
                ["文化人類学"],
                ["アジア研究"],
                ["生物学"],
                ["経営学"],
                ["化学"],
                ["教育学"],
                ["経済学"],
                ["環境学"],
                ["グローバル研究"],
                ["ジェンダー・セクシャリティー研究"],
                ["歴史学"],
                ["国際関係学"],
                ["情報科学"],
                ["日本研究"],
                ["法学"],
                ["言語教育"],
                ["文学"],
                ["言語学"],
                ["メディア・コミュニケーション・文化"],
                ["数学"],
                ["音楽"],
                ["平和研究"],
                ["哲学・宗教学"],
                ["物理学"],
                ["政治学"],
                ["公共政策"],
                ["心理学"],
                ["社会学"],
                ["その他"]
                ]) %>
                </div>
            </div>
            
                <div class="profile-left">
                    <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>キーワード</div>
                    <div><%= text_field_tag 'post[keyword_list]', @posts.keyword_list.join(',' || '、'), "data-role" => "tagsinput", :class =>"form",style: :"width:100%", placeholder: :"半角コンマ区切りで論文のキーワードを入力すると、タグとして表示されるようになります。（例）教育社会学,塾,教育格差,教育の正当化機能" %></div>
                </div>
                
            <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>論文紹介</div>
                <div style="padding:20px"> <%= f.text_area :summary, style: :"width:100%", placeholder: :"ここに論文の要約を記入してください。"  %></div>
            </div>
    
             <div class="profile-left">
                <div style="border-bottom:1px solid #606060"><i class="fa fa-info-circle" aria-hidden="true"></i>【任意】PDFを添付</div>
                <div style="padding:20px"><%= f.file_field :file do%>PDFを選択<% end %></div>
             </div>
             
              <div class="profile-left">
                <div style="border-bottom:1px solid #606060">
                    （注)</br>
                    論文には、個人情報が含まれている可能性があります。気になる方は<%= link_to "利用規約", terms_path %>をご確認ください。
                </div>
             </div>
             <%= f.submit '利用規約に同意して、投稿する', class: :"btn btn-info btn-block" %>
            <% end %>
    </div>
    
    <div class="col-xs-12 col-sm-12 col-md-12 profile" id="user_profile">
        <h2 class="profile-header">WordファイルをPDFにする場合</h2>
            <ul>
                <li>「PDF」形式で保存したいファイルを開き、「ファイル」タブをクリック</li>
                <li>保存したいフォルダーを決めます。</li>
                <li>「名前を付けて保存」画面が表示されるので「ファイルの種類」を「PDF(*.pdf)」に変更して「ファイル名」を決めます</li>
                <li>「保存」ボタンをクリック。</li>
            </ul>
        <h2 class="profile-header">PDFの注意点</h2>
            <ul>
                <li>卒業論文には実名が記入されている場合があります。</li>
                <li>プライバシーの観点から、必ず個人情報が含まれていないか確認してください</li>
            </ul>
    </div>
    
    
 </div>

app/views/posts/papermajor.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1"  id="user_profile"> <!--ここに、共通の友人一覧を表示-->
        <div class="profile-header" style="text-align:center;padding:20px 0"><%= params[:major] %> (<%= @posts.count%>)</div>
    </div>
<!-------------------------------------------------論文ページ------------------------------------------------------------->
<% @posts.each do |post| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class="profile-header"><%= link_to post.title, post_path(post)%></div>
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>キーワード
                    <% post.keyword_list.each do |tag| %>
                        <span class="tag-button"><%= tag %></span>
                    <% end %>
                </div>
                <div class ="profile-left"><%= image_tag post.user.attachment, :size =>"30x30" %> <%= post.user.username %></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= post.major %></div>
                <div class="profile-left"><i class="fa fa-heart" aria-hidden="true"></i>(<%= post.votes_for.size %>)　<i class="fa fa-comment" aria-hidden="true"></i> (<%= post.comments.count %>)</div>
                <div class="profile-left"></div>
              <% if post.user == current_user %>
                  <%= link_to "編集する", edit_post_path(post), class: :"button-radius" %>
                  <%= link_to "消去する", post_path(post), method: :delete, class: :"button-radius" %>
              <% end %>
    </div>
    <% end %>
    
</div>

app/views/posts/show.html.erb
<% provide(:title, "#{@posts.title}") %>

<div class="row">
<!-------------------------------------------------論文ページ------------------------------------------------------------->
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="user_profile" style="margin-top:50px">
          <%= link_to "ユーザー一覧",users_path %> / <%= image_tag @posts.user.attachment, :size =>"30x30" %><%= link_to @posts.user.username, user_path(@posts.user) %> / <%= link_to @posts.title, post_path(@posts) %>
        </div>
        
        <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="posts-index"> 
                <div class=" profile-header"><%= link_to @posts.title, post_path(@posts)%></div>
                <div class ="profile-left"><span class="glyphicon glyphicon glyphicon-book" aria-hidden="true"></span><%= @posts.major %></div>
                <div class="profile-left"><i class="fa fa-tags" aria-hidden="true"></i>キーワード
                  <% @posts.keyword_list.each do |tag| %>
                      <span class="tag-button"> <%= tag %></span>
                  <% end %>
                 </div>
                <div class ="profile-left"><%= link_to user_path(@posts.user) do%><%= image_tag @posts.user.attachment, :size =>"30x30" %><%= @posts.user.username %><% end %></div>
                <div class="profile-left"><i class="fa fa-info-circle" aria-hidden="true"></i> 要約</div>
                <div class="profile-left"><%= @posts.summary %></div>
                <div class="profile-left">
                    <a href="#comment-form"><i class="fa fa-comment fa-2x colored-star"></i><%= @posts.comments.count %></a> 
                    <a href="https://twitter.com/share" class="twitter-share-button" data-size="large" data-hashtags="CurioCity">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    <% unless current_user.voted_for? @posts %>
                        <%= link_to like_post_path(@posts), method: :put do%><i class="fa fa-star-o fa-2x colored-star" aria-hidden="true"></i><%end%> <%= @posts.votes_for.size %>
                    <% else %>
                        <%= link_to dislike_post_path(@posts), method: :put do%><i class="fa fa-star fa-2x colored-star" aria-hidden="true"></i><%end%> <%= @posts.votes_for.size %>
                    <% end %>
                    
                      <%= link_to asset_path(@posts.file),:target=>["_blank"]  do%> <i class="fa fa-file-pdf-o fa-2x pdf-color" aria-hidden="true"></i> <%end%>
                
                </div>
                <div>
                      <% if @posts.user == current_user %>
                        <%= link_to "編集する", edit_post_path(@posts), class: :"button-radius" %>
                        <%= link_to "消去する", post_path(@posts), method: :delete, class: :"button-radius" %>
                    <% end %>
                </div>
        </div>
              

<!------------------------------------------------------------------------------------------------------------->

<% if @posts.comments.present?%>
<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" style="text-align:center; font-size:24px">コメント(<%= @posts.comments.count %>)</div>
<!-- 表示comment ----------------------->  
  <% @posts.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1" id="comment-content"> 
      <div class="col-md-2">
        <div><%= link_to user_path(comment.user) do %> <%= image_tag comment.user.attachment, :size =>"30x30" %><%= comment.user.username%>さん<%end%></div>
        <div><%=comment.user.major%></div>
      </div>
      
      <div class="col-md-10">
          <%= comment.text.html_safe %>
        <div><small><%= time_ago_in_words(comment.created_at)%>前</small>
        <% unless current_user.voted_for? comment %>
          <%= link_to like_comment_path(comment), method: :put do%><i class="fa fa-star-o  fa-2x colored-star" aria-hidden="true"></i><% end %> <%= comment.votes_for.size %>
        <% else %>
          <%= link_to dislike_comment_path(comment), method: :put do%><i class="fa fa-star fa-2x uncolored-star" aria-hidden="true"></i><%end%> <%= comment.votes_for.size %>
        <% end %>
          <% if comment.user == current_user %>
            <%= link_to 'コメントを消す', post_comment_path(post_id: @posts.id, id: comment.id), method: :delete, class: :"tag-button" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<!--コメントを入力する -->  


<%= form_for Comment.new, url: post_comments_path(@posts), method: :post do |f| %>
<div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile" style="text-align:center">コメントする</div>
  <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1 profile" id="user_profile"> 
    <%= f.cktext_area :text%>
    <div class="profile-left">
        <div><%= f.submit 'コメントする', class: :"btn btn-primary" %></div>
    </div>

</div>  
<% end %>

</div>